name: CI with Docker
run-name: CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Run linting inside container
        run: docker run my-python-app pylint src ||true

      #- name: Run application or tests
      #  run: docker run my-python-app python -m unittest discover -s src/tests

      - name: Generate and extract index.html
        run: |
          mkdir -p public
          docker create --name gen my-python-app
          docker cp gen:/app/index.html ./public/index.html
          docker rm gen

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4